# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_call:
  
permissions:
  contents: read

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradle Setup
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1.1
    - name: Build with Gradle
      run: gradle build -x test
    - name: Publish war for deployment
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: War files
        path: app/build/libs  
  
  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradle Setup
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1.1
    - name: Run tests
      run: gradle test
    - name: Publish test reports in HTML
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: HTML Test Reports
        path: app/build/reports/tests/test

    - name: Publish test reports in XML
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: XML Test Reports
        path: app/build/test-results/test/*.xml
     
    - name: Pushes test file
      if: always()
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'app/build/test-results/test/TEST-sample.java.app.AppTest.xml'
        destination_repo: 'dmnemec/release-test'
        user_email: 'ashutosh.parida@hpe.com'
        user_name: 'ashu-parida-hpe' 
                